#!/bin/bash

IP:${GREEN} $IP
# OS
os=$(cat /etc/os-release | grep PRETTY_NAME | cut -d "=" -f 2- | tr -d '"')
echo "OS: $os"

# RAM
ram_total=$(free -m | awk 'NR==2 {print $2}')
ram_used=$(free -m | awk 'NR==2 {print $3}')
echo "RAM: $ram_used MB / $ram_total MB"

# DATE
date=$(date)
echo "DATE: $date"

# UPTIME
uptime=$(uptime -p)
echo "UPTIME: $uptime"

# ISP
isp=$(curl -s ip-api.com/json/$(curl -s ifconfig.me) | sed 's/.*"isp":"\([^"]*\).*/\1/')
echo "ISP: $isp"

# City
city=$(curl -s ip-api.com/json/$(curl -s ifconfig.me) | sed 's/.*"city":"\([^"]*\).*/\1/')
echo "City: $city"
