#!/bin/bash
#Zahid - PowerMX
IP=`curl -4 icanhazip.com`;
distribution=`( lsb_release -ds || cat /etc/*release || uname -om ) 2>/dev/null | head -n1`;
Network=`ip -4 route ls|grep default|grep -Po '(?<=dev )(\S+)'|head -1`;
ports=`netstat -tunlp | grep zivpn | grep ::: | awk '{print substr($4,4); }' > /tmp/udpzivpn.txt && echo | cat /tmp/udpzivpn.txt | tr '\n' ' ' > /tmp/udpzivpnports.txt && cat /tmp/udpzivpnports.txt`;
#colors
RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
PURPLE='\033[1;35m'
CYAN='\033[1;36m'
GRAY='\033[1;37m'
WHITE='\033[1;37m'
RESET='\033[0m'
#menu
while true; do
  if [ $(id -u) -eq 0 ]; then
    clear
  else
    echo -e "Run the script as root user"
    exit
  fi
#installv1
function installv1(){
echo -e "${RED} ────────────── /// ─────────────── "
echo -e "${YELLOW}This option will install ZIVPN version 1, UDP port range will be 20000:50000 redirected to 5666"
echo -e "${YELLOW}Continue?"
while [[ ${yesno} != @(s|S|y|Y|n|N) ]]; do
read -p "[S/N]: " yesno
tput cuu1 && tput dl1
done
if [[ ${yesno} = @(s|S|y|Y) ]]; then
echo -e "${YELLOW}INSTALLING.."
bash <(curl -fsSL https://raw.githubusercontent.com/powermx/zivpn/main/ziv1.sh)
fi
}
#installv2
function installv2(){
echo -e "${RED} ────────────── /// ─────────────── "
echo -e "${YELLOW}This option will install ZIVPN version 2 AMD, UDP port range will be 6000:19999 redirected to 5667"
echo -e "${YELLOW}Continue?"
while [[ ${yesno} != @(s|S|y|Y|n|N) ]]; do
read -p "[S/N]: " yesno
tput cuu1 && tput dl1
done
if [[ ${yesno} = @(s|S|y|Y) ]]; then
echo -e "${YELLOW}INSTALLING.."
bash <(curl -fsSL https://raw.githubusercontent.com/powermx/zivpn/main/ziv2.sh)
fi
}
#installv3
function installv3(){
echo -e "${RED} ────────────── /// ─────────────── "
echo -e "${YELLOW}This option will install ZIVPN version 2 ARM, UDP port range will be 6000:19999 redirected to 5667"
echo -e "${YELLOW}Continue?"
while [[ ${yesno} != @(s|S|y|Y|n|N) ]]; do
read -p "[S/N]: " yesno
tput cuu1 && tput dl1
done
if [[ ${yesno} = @(s|S|y|Y) ]]; then
echo -e "${YELLOW}INSTALLING.."
bash <(curl -fsSL https://raw.githubusercontent.com/powermx/zivpn/main/ziv3.sh)
fi
}
#uninstall
function uninstall(){
echo -e "${RED} ────────────── /// ─────────────── "
echo -e "${YELLOW}This option will uninstall the ZIVPN server in any of its versions"
echo -e "${YELLOW}Continue?"
while [[ ${yesno} != @(s|S|y|Y|n|N) ]]; do
read -p "[S/N]: " yesno
tput cuu1 && tput dl1
done
if [[ ${yesno} = @(s|S|y|Y) ]]; then
echo -e "${YELLOW}UNINSTALLING.."
bash <(curl -fsSL https://raw.githubusercontent.com/powermx/zivpn/main/uninstall.sh)
fi
}
#start
function startzivpn(){
echo -e "${RED} ────────────── /// ─────────────── "
echo -e "${YELLOW}This option will start the ZiVPN server"
echo -e "${YELLOW}Continue?"
while [[ ${yesno} != @(s|S|y|Y|n|N) ]]; do
read -p "[S/N]: " yesno
tput cuu1 && tput dl1
done
if [[ ${yesno} = @(s|S|y|Y) ]]; then
echo -e "${YELLOW}STARTING.."
    if [[ ${yesno} = @(s|S|y|Y) ]]; then
        echo -e "${YELLOW}Checking for ZiVPN services..."
        
        if [[ -f /etc/systemd/system/zivpn.service ]]; then
            echo -e "${YELLOW}Starting ZiVPN service..."
            sudo systemctl start zivpn.service
        fi
        if [[ -f /etc/systemd/system/zivpn_backfill.service ]]; then
            echo -e "${YELLOW}Starting ZiVPN Backfill service..."
            sudo systemctl start zivpn_backfill.service
        fi
        
        echo -e "${YELLOW}DONE!"
    fi
fi
}
#stop
function stopzivpn(){
echo -e "${RED} ────────────── /// ─────────────── "
echo -e "${YELLOW}This option will stop the ZiVPN server"
echo -e "${YELLOW}Continue?"
while [[ ${yesno} != @(s|S|y|Y|n|N) ]]; do
read -p "[S/N]: " yesno
tput cuu1 && tput dl1
done
if [[ ${yesno} = @(s|S|y|Y) ]]; then
echo -e "${YELLOW}STOPPING.."
    if [[ ${yesno} = @(s|S|y|Y) ]]; then
        echo -e "${YELLOW}Checking for ZiVPN services..."
        
        if [[ -f /etc/systemd/system/zivpn.service ]]; then
            echo -e "${YELLOW}Starting ZiVPN service..."
            sudo systemctl stop zivpn.service
        fi
        if [[ -f /etc/systemd/system/zivpn_backfill.service ]]; then
            echo -e "${YELLOW}Starting ZiVPN Backfill service..."
            sudo systemctl stop zivpn_backfill.service
        fi
        
        echo -e "${YELLOW}DONE!"
    fi
fi
}
#restart
function restartzivpn(){
echo -e "${RED} ────────────── /// ─────────────── "
echo -e "${YELLOW}This option will restart the ZiVPN server"
echo -e "${YELLOW}Continue?"
while [[ ${yesno} != @(s|S|y|Y|n|N) ]]; do
read -p "[S/N]: " yesno
tput cuu1 && tput dl1
done
if [[ ${yesno} = @(s|S|y|Y) ]]; then
echo -e "${YELLOW}RESTARTING.."
    if [[ ${yesno} = @(s|S|y|Y) ]]; then
        echo -e "${YELLOW}Checking for ZiVPN services..."
        
        if [[ -f /etc/systemd/system/zivpn.service ]]; then
            echo -e "${YELLOW}Starting ZiVPN service..."
            sudo systemctl restart zivpn.service
        fi
        if [[ -f /etc/systemd/system/zivpn_backfill.service ]]; then
            echo -e "${YELLOW}Starting ZiVPN Backfill service..."
            sudo systemctl restart zivpn_backfill.service
        fi
        
        echo -e "${YELLOW}DONE!"
    fi
fi
}
  if [[ $1 == "" ]]; then
    clear && printf '\e[3J'
echo -e "${GRAY}${RED}${GRAY}${RED}┌─────── HAMZA TECH ────────┐ "
echo -e "${YELLOW}│ ${WHITE}SYS OS :${GREEN} $distribution "
echo -e "${YELLOW}│ ${WHITE}IP :${GREEN} $IP "
echo -e "${YELLOW}│ ${WHITE}Network:${GREEN} $Network "
echo -e "${YELLOW}│ ${WHITE}Running:${GREEN} $ports "
echo -e "${GRAY}${RED}${GRAY}${RED}┌──────────────── ZIVPN ────────────────┐ "
echo -e "${RED}${ORANGE}│ ${YELLOW}${RED} 1.${RED}INSTALL ZIVPN V1  5.START ZIVPN
${YELLOW}${RED}│ ${YELLOW}${RED} 2.${RED}INSTALL ZIVPN V2  6.STOP ZIVPN
${YELLOW}${RED}│ ${YELLOW}${RED} 3.${RED}INSTALL ZIVPN V3  7.RECALIN ZIVPN
${YELLOW}${RED}│ ${YELLOW}${RED} 4.${RED}RESTART SCRIPT    0.EXIT SCRIPT
${GRAY}${RED}${GRAY}${RED}└───────────────────────────────────────┘ "
echo ""
echo -e "       ╔══════════════════════════════════════╗"
echo -e "       ║  POWERD BY CHANNEL t.me/free_net_mrr ║" | lolcat
echo -e "       ║   2019-2025 © All Rights Reserved .  ║"
echo -e "       ╚════════════════•⊱✦⊰•═════════════════╝"
echo ""
echo -e "${YELLOW} Select From Options [ 1 - 7 ] :      ${YELLOW}"
read -p " : " option
tput cuu1 >&2 && tput dl1 >&2
else
option=$1
fi
case $option in
  1 | 01 )
   installv1;;
  2 | 02 )
   installv2;;
  3 | 03 )
   installv3;;
  4 | 04)
   uninstall;;
  5 | 05)
   startzivpn;;
  6 | 06)
   stopzivpn;;
  7 | 07)
   restartzivpn;;
  0)
  exit;;
  *)
  continue;;
  esac
  break
  done
